name: Greeting
on:
  pull_request:
    types:
      - opened

jobs:
  greeting:
    name: Issue a greeting comment upon PR
    runs-on: ubuntu-latest

    steps:
      - name: Issue the greeting comment
        run: |
          echo "Henlooo"
