name: Greeting
on:
  pull_request:
    types:
      - opened

jobs:
  greeting:
    name: Issue a greeting comment upon PR
    runs-on: ubuntu-latest

    steps:
      - name: Issue the greeting comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Henlooo!
